import type { LucideIcon } from 'lucide-react'
import {
  Activity,
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  BatteryCharging,
  BatteryFull,
  Bell,
  BookOpen,
  Bot,
  Box,
  Brain,
  Calendar,
  Camera,
  Check,
  CheckCheck,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  Circle,
  Copy,
  CircleOff,
  Clock,
  Container,
  Cpu,
  Crosshair,
  Database,
  Download,
  Edit2,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileText,
  Folder,
  GitCommit,
  Globe,
  Grid,
  HardDrive,
  HelpCircle,
  History,
  Home,
  Image,
  Inbox,
  Info,
  Layers,
  LayoutDashboard,
  List,
  Loader2,
  LogOut,
  Map,
  MapPin,
  Maximize2,
  Minimize2,
  Move,
  Menu,
  MessageSquare,
  Monitor,
  Moon,
  MoreHorizontal,
  Network,
  PanelLeft,
  PanelRight,
  Pencil,
  Phone,
  PhoneCall,
  PhoneIncoming,
  PhoneMissed,
  PhoneOff,
  PhoneOutgoing,
  Plus,
  Power,
  Radio,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Shield,
  ShieldCheck,
  Smartphone,
  Search,
  Server,
  Settings,
  Sliders,
  Sparkles,
  Sun,
  Terminal,
  TextCursor,
  Thermometer,
  Trash,
  Trash2,
  Upload,
  User,
  Users,
  Video,
  VideoOff,
  Wifi,
  WifiOff,
  X,
  XCircle,
  Zap,
} from 'lucide-react'

export interface IconRegistryEntry {
  component: LucideIcon
  keywords?: string[]
}

export type IconName = keyof typeof iconRegistry

export const iconRegistry: Record<string, IconRegistryEntry> = {
  activity: { component: Activity, keywords: ['monitor', 'chart'] },
  'alert-triangle': { component: AlertTriangle, keywords: ['warning', 'danger'] },
  'arrow-down': { component: ArrowDown, keywords: ['download', 'decrease'] },
  download: { component: Download, keywords: ['download', 'save'] },
  play: { component: Power, keywords: ['play', 'start', 'run'] },
  'arrow-up': { component: ArrowUp, keywords: ['upload', 'increase'] },
  'battery-charging': { component: BatteryCharging, keywords: ['battery', 'charge', 'power'] },
  'battery-full': { component: BatteryFull, keywords: ['battery', 'power'] },
  bell: { component: Bell, keywords: ['notification', 'alert'] },
  'book-open': { component: BookOpen, keywords: ['documentation', 'knowledge', 'book'] },
  bot: { component: Bot, keywords: ['assistant', 'ai', 'kuro', 'robot'] },
  box: { component: Box, keywords: [] },
  brain: { component: Brain, keywords: ['memory', 'memories', 'ai', 'brain', 'mind'] },
  calendar: { component: Calendar, keywords: ['calendar', 'date', 'schedule', 'baikal'] },
  sparkles: { component: Sparkles, keywords: ['ai', 'magic', 'assistant'] },
  camera: { component: Camera, keywords: ['camera', 'webcam', 'video', 'feed', 'photo'] },
  crosshair: { component: Crosshair, keywords: ['target', 'locate', 'center'] },
  video: { component: Video, keywords: ['stream', 'record', 'media'] },
  'video-off': { component: VideoOff, keywords: ['disable', 'stop'] },
  'maximize-2': { component: Maximize2, keywords: ['fullscreen', 'expand'] },
  'minimize-2': { component: Minimize2, keywords: ['exit', 'compress'] },
  'rotate-ccw': { component: RotateCcw, keywords: ['reset', 'refresh'] },
  'rotate-cw': { component: RotateCw, keywords: ['rotate', 'orientation', 'turn'] },
  smartphone: { component: Smartphone, keywords: ['mobile', 'portrait', 'phone'] },
  sliders: { component: Sliders, keywords: ['controls', 'settings', 'resolution'] },
  check: { component: Check, keywords: ['success', 'done', 'save', 'confirm'] },
  'check-check': { component: CheckCheck, keywords: ['delivered', 'read', 'sent', 'double-check'] },
  'check-circle': { component: CheckCircle, keywords: ['success', 'done', 'healthy'] },
  'check-circle-2': { component: CheckCircle2, keywords: ['success', 'done'] },
  'chevron-down': { component: ChevronDown, keywords: ['expand', 'open'] },
  'chevron-left': { component: ChevronLeft, keywords: ['back', 'previous'] },
  'chevron-right': { component: ChevronRight, keywords: ['forward', 'next'] },
  'chevrons-left': { component: ChevronsLeft, keywords: ['first'] },
  'chevrons-right': { component: ChevronsRight, keywords: ['last'] },
  circle: { component: Circle, keywords: ['dot', 'empty'] },
  'circle-off': { component: CircleOff, keywords: ['offline', 'disconnected'] },
  clock: { component: Clock, keywords: ['time', 'history', 'timestamp'] },
  container: { component: Container, keywords: ['docker', 'box'] },
  copy: { component: Copy, keywords: ['duplicate'] },
  cpu: { component: Cpu, keywords: ['processor', 'chip'] },
  database: { component: Database, keywords: ['database', 'storage', 'data', 'db'] },
  'edit-2': { component: Edit2, keywords: ['rename', 'edit', 'pencil', 'write'] },
  'edit-3': { component: Edit3, keywords: ['rename', 'edit', 'pencil', 'write'] },
  'external-link': { component: ExternalLink, keywords: ['external', 'link', 'open'] },
  eye: { component: Eye, keywords: ['show', 'visible'] },
  'eye-off': { component: EyeOff, keywords: ['hide', 'invisible'] },
  file: { component: File, keywords: ['document'] },
  'file-text': { component: FileText, keywords: ['log', 'audit', 'document'] },
  folder: { component: Folder, keywords: ['directory'] },
  'git-commit': { component: GitCommit, keywords: ['version', 'commit', 'route'] },
  globe: { component: Globe, keywords: ['world', 'internet'] },
  grid: { component: Grid, keywords: ['grid', 'tiles', 'layout'] },
  'hard-drive': { component: HardDrive, keywords: ['storage', 'disk'] },
  'help-circle': { component: HelpCircle, keywords: ['help', 'question'] },
  history: { component: History, keywords: ['history', 'recent', 'clock', 'time'] },
  home: { component: Home, keywords: ['dashboard', 'index'] },
  image: { component: Image, keywords: ['photo', 'picture', 'gallery'] },
  inbox: { component: Inbox, keywords: ['empty', 'no data', 'nothing'] },
  info: { component: Info, keywords: ['information'] },
  layers: { component: Layers, keywords: ['history', 'drawer', 'stack', 'tabs'] },
  'layout-dashboard': { component: LayoutDashboard, keywords: ['dashboard', 'grid'] },
  list: { component: List, keywords: ['list', 'details'] },
  'loader-2': { component: Loader2, keywords: ['spinner', 'loading'] },
  'log-out': { component: LogOut, keywords: ['logout', 'exit'] },
  map: { component: Map, keywords: ['map', 'location', 'gps'] },
  'map-pin': { component: MapPin, keywords: ['location', 'gps', 'pin', 'place'] },
  move: { component: Move, keywords: ['move', 'relocate'] },
  menu: { component: Menu, keywords: ['hamburger', 'sidebar'] },
  'message-square': { component: MessageSquare, keywords: ['chat', 'message', 'conversation', 'thread', 'sms'] },
  monitor: { component: Monitor, keywords: ['screen', 'display'] },
  moon: { component: Moon, keywords: ['dark', 'night'] },
  'more-horizontal': { component: MoreHorizontal, keywords: ['more', 'overflow'] },
  network: { component: Network, keywords: ['network', 'connections'] },
  'panel-left': { component: PanelLeft, keywords: ['sidebar', 'toggle'] },
  'panel-right': { component: PanelRight, keywords: ['sidebar', 'toggle'] },
  pencil: { component: Pencil, keywords: ['edit', 'rename', 'write'] },
  phone: { component: Phone, keywords: ['call', 'telephone', 'mobile'] },
  'phone-call': { component: PhoneCall, keywords: ['call', 'dial', 'voice'] },
  'phone-incoming': { component: PhoneIncoming, keywords: ['call', 'incoming', 'received'] },
  'phone-outgoing': { component: PhoneOutgoing, keywords: ['call', 'outgoing', 'dialed'] },
  'phone-missed': { component: PhoneMissed, keywords: ['call', 'missed'] },
  'phone-off': { component: PhoneOff, keywords: ['call', 'blocked', 'rejected', 'hung up'] },
  plus: { component: Plus, keywords: ['add', 'create', 'new'] },
  power: { component: Power, keywords: ['power', 'shutdown', 'reboot', 'restart', 'off', 'turn off'] },
  radio: { component: Radio, keywords: ['broadcast', 'live', 'signal', 'radio', 'tracking'] },
  'refresh-cw': { component: RefreshCw, keywords: ['refresh', 'reload', 'sync'] },
  search: { component: Search, keywords: ['find', 'lookup'] },
  server: { component: Server, keywords: ['host', 'system'] },
  settings: { component: Settings, keywords: ['preferences', 'config'] },
  shield: { component: Shield, keywords: ['security', 'admin', 'privacy', 'safe', 'protection'] },
  'shield-check': { component: ShieldCheck, keywords: ['security', 'privacy', 'safe', 'verified'] },
  sun: { component: Sun, keywords: ['light', 'bright'] },
  terminal: { component: Terminal, keywords: ['console', 'shell'] },
  'text-cursor': { component: TextCursor, keywords: ['rename', 'edit', 'cursor'] },
  thermometer: { component: Thermometer, keywords: ['temperature', 'heat'] },
  trash: { component: Trash, keywords: ['delete', 'remove', 'trash'] },
  'trash-2': { component: Trash2, keywords: ['delete', 'remove'] },
  upload: { component: Upload, keywords: ['upload'] },
  user: { component: User, keywords: ['profile', 'account'] },
  users: { component: Users, keywords: ['team', 'people'] },
  wifi: { component: Wifi, keywords: ['network', 'wireless', 'tailscale'] },
  'wifi-off': { component: WifiOff, keywords: ['offline', 'disconnected'] },
  x: { component: X, keywords: ['close', 'cancel'] },
  'x-circle': { component: XCircle, keywords: ['error', 'danger', 'failed'] },
  zap: { component: Zap, keywords: ['power', 'lightning', 'quick'] },
}

export function getIcon(name: IconName): LucideIcon {
  const entry = iconRegistry[name]
  if (!entry) {
    console.warn(`AppIcon: "${name}" not found in registry`)
    return HelpCircle
  }
  return entry.component
}

export function searchIcons(query: string): string[] {
  const q = query.toLowerCase()
  return Object.entries(iconRegistry)
    .filter(([name, entry]) => {
      if (name.includes(q)) return true
      return entry.keywords?.some((k) => k.includes(q))
    })
    .map(([name]) => name)
}
