export { Text } from './Text'
export type { TextProps } from './Text'
export { Heading } from './Heading'
export type { HeadingProps } from './Heading'
export { Caption } from './Caption'
export type { CaptionProps } from './Caption'
export { Label } from './Label'
export type { LabelProps } from './Label'
export { Value } from './Value'
export type { ValueProps } from './Value'
export { Code } from './Code'
export type { CodeProps } from './Code'
